# $Id: testconf.py.in 354172 2005-12-05 20:38:53Z nlehuen $



# This file is autogenerated by ./configure



# Path to the Apache executable
HTTPD="/usr/local/apache2/bin/httpd"

# Path to the current directory
TESTHOME="/home/dds/workspace/httpd-2.2.25/modules/mod_python-3.3.1/test"

# Path to the Apache modules directory
LIBEXECDIR="/usr/local/apache2/modules"

# Path to the mod_python.so file, should be in the apache modules directory.
MOD_PYTHON_SO="/home/dds/workspace/httpd-2.2.25/modules/mod_python-3.3.1/src/mod_python.so"

# makes emacs go into python mode
### Local Variables:
### mode:python
### End:
