top_srcdir   = /home/dds/workspace/httpd-2.2.25
top_builddir = /home/dds/workspace/httpd-2.2.25
srcdir       = /home/dds/workspace/httpd-2.2.25/modules/mappers
builddir     = /home/dds/workspace/httpd-2.2.25/modules/mappers
VPATH        = /home/dds/workspace/httpd-2.2.25/modules/mappers

include $(top_srcdir)/build/special.mk

