top_srcdir   = /home/dds/workspace/httpd-2.2.25
top_builddir = /home/dds/workspace/httpd-2.2.25
srcdir       = /home/dds/workspace/httpd-2.2.25/modules
builddir     = /home/dds/workspace/httpd-2.2.25/modules
VPATH        = /home/dds/workspace/httpd-2.2.25/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

