top_srcdir   = /home/dds/workspace/httpd-2.2.25
top_builddir = /home/dds/workspace/httpd-2.2.25
srcdir       = /home/dds/workspace/httpd-2.2.25/modules/metadata
builddir     = /home/dds/workspace/httpd-2.2.25/modules/metadata
VPATH        = /home/dds/workspace/httpd-2.2.25/modules/metadata

include $(top_srcdir)/build/special.mk

