top_srcdir   = /home/dds/workspace/httpd-2.2.25
top_builddir = /home/dds/workspace/httpd-2.2.25
srcdir       = /home/dds/workspace/httpd-2.2.25/modules/generators
builddir     = /home/dds/workspace/httpd-2.2.25/modules/generators
VPATH        = /home/dds/workspace/httpd-2.2.25/modules/generators

include $(top_srcdir)/build/special.mk

