top_srcdir   = /home/dds/workspace/httpd-2.2.25
top_builddir = /home/dds/workspace/httpd-2.2.25
srcdir       = /home/dds/workspace/httpd-2.2.25/server/mpm/prefork
builddir     = /home/dds/workspace/httpd-2.2.25/server/mpm/prefork
VPATH        = /home/dds/workspace/httpd-2.2.25/server/mpm/prefork

LTLIBRARY_NAME    = libprefork.la
LTLIBRARY_SOURCES = prefork.c

include $(top_srcdir)/build/ltlib.mk
