top_srcdir   = /home/dds/workspace/httpd-2.2.25
top_builddir = /home/dds/workspace/httpd-2.2.25
srcdir       = /home/dds/workspace/httpd-2.2.25/modules/echo
builddir     = /home/dds/workspace/httpd-2.2.25/modules/echo
VPATH        = /home/dds/workspace/httpd-2.2.25/modules/echo

include $(top_srcdir)/build/special.mk

