top_srcdir   = /home/dds/workspace/httpd-2.2.25
top_builddir = /home/dds/workspace/httpd-2.2.25
srcdir       = /home/dds/workspace/httpd-2.2.25/modules/filters
builddir     = /home/dds/workspace/httpd-2.2.25/modules/filters
VPATH        = /home/dds/workspace/httpd-2.2.25/modules/filters

include $(top_srcdir)/build/special.mk

