top_srcdir   = /home/dds/workspace/httpd-2.2.25
top_builddir = /home/dds/workspace/httpd-2.2.25
srcdir       = /home/dds/workspace/httpd-2.2.25/modules/aaa
builddir     = /home/dds/workspace/httpd-2.2.25/modules/aaa
VPATH        = /home/dds/workspace/httpd-2.2.25/modules/aaa

include $(top_srcdir)/build/special.mk

