top_srcdir   = /home/dds/workspace/httpd-2.2.25
top_builddir = /home/dds/workspace/httpd-2.2.25
srcdir       = /home/dds/workspace/httpd-2.2.25/modules/cache
builddir     = /home/dds/workspace/httpd-2.2.25/modules/cache
VPATH        = /home/dds/workspace/httpd-2.2.25/modules/cache

include $(top_srcdir)/build/special.mk

