top_srcdir   = /home/dds/workspace/httpd-2.2.25
top_builddir = /home/dds/workspace/httpd-2.2.25
srcdir       = /home/dds/workspace/httpd-2.2.25/os
builddir     = /home/dds/workspace/httpd-2.2.25/os
VPATH        = /home/dds/workspace/httpd-2.2.25/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
