top_srcdir   = /home/dds/workspace/httpd-2.2.25
top_builddir = /home/dds/workspace/httpd-2.2.25
srcdir       = /home/dds/workspace/httpd-2.2.25/modules/mobileserver
builddir     = /home/dds/workspace/httpd-2.2.25/modules/mobileserver
VPATH        = /home/dds/workspace/httpd-2.2.25/modules/mobileserver

include $(top_srcdir)/build/special.mk

