top_srcdir   = /home/dds/workspace/httpd-2.2.25
top_builddir = /home/dds/workspace/httpd-2.2.25
srcdir       = /home/dds/workspace/httpd-2.2.25/modules/http
builddir     = /home/dds/workspace/httpd-2.2.25/modules/http
VPATH        = /home/dds/workspace/httpd-2.2.25/modules/http

include $(top_srcdir)/build/special.mk

