top_srcdir   = /home/dds/workspace/httpd-2.2.25
top_builddir = /home/dds/workspace/httpd-2.2.25
srcdir       = /home/dds/workspace/httpd-2.2.25/server/mpm
builddir     = /home/dds/workspace/httpd-2.2.25/server/mpm
VPATH        = /home/dds/workspace/httpd-2.2.25/server/mpm

SUBDIRS = $(MPM_SUBDIR_NAME)

include $(top_builddir)/build/rules.mk
